AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy Docker container using AWS CloudFormation

Resources:
  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: MyECSService
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 1
      LaunchType: EC2

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: MyTaskDefinition
      ContainerDefinitions:
        - Name: MyContainer
          Image: hello-app
          Memory: 512
          PortMappings:
            - ContainerPort: 80
              HostPort: 80

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MyECSCluster

Outputs:
  ServiceURL:
    Value: !Sub "http://${MyECSService.LoadBalancer.LoadBalancerDnsName}"
    Description: URL of the deployed service